apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: asia.gcr.io/satopj0614/tomcat:9.0    # Tomcat image
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: tomcat-config
              mountPath: /usr/local/tomcat/conf/server.xml
              subPath: server.xml
            - name: tomcat-config
              mountPath: /usr/local/tomcat/conf/context.xml
              subPath: context.xml
      volumes:
        - name: tomcat-config
          configMap:
            name: tomcat-config  # ConfigMap 