apiVersion: batch/v1
kind: CronJob
metadata:
  name: update-tomcat-image
spec:
  schedule: "*/5 * * * *"  # 5分に一回実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: updater
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - |
              # ConfigMapからスクリプトを取得して実行する
              script=$(cat /etc/cronjob-scripts/cronjob.sh)
              eval "$script"
          restartPolicy: OnFailure
          volumes:
          - name: cronjob-scripts-volume
            configMap:
              name: cronjob-scripts
              items:
              - key: cronjob.sh
                path: cronjob.sh
