apiVersion: batch/v1
kind: CronJob
metadata:
  name: tomcat-image-update
spec:
  schedule: "*/1 * * * *"  # 1分に一回実行
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest  # kubectl を実行するコンテナイメージ
            command:
            - "kubectl"
            - "set"
            - "image"
            - "deployment/tomcat-deployment"
            - "tomcat=tomcat:10.0"  # 更新したいイメージとバージョンを指定
          restartPolicy: OnFailure
